### ISSUE TITLE
Validity of negative coordinate values

### ISSUE THREAD

**Issue by aschampion** [saalfeldlab/n5#28]
The reference N5 implementation takes dimensions, block size and block coordinates as signed values.

1. Are negative dimensions valid?
2. Are negative block sizes valid?
3. Are negative block coordinates valid? (In directories `-1/-2/3`, etc.) Only if dimension xor block size is negative for the given block axis?

e: In case it's not obvious, my preference is the answer for all 3 is "no".

**Comment by axtimwalde** [comment]
I think we shouldn't require negative coordinates to work.  The reference implementation uses Java primitive types which don't exist as unsigned, and I am unwilling to test 'defensively' for stuff that may just work somehow even if not intended.  If negative coordinates were desired, a min and max range instead of a dimensions field would be appropriate.  However, since it is possible to do it, you may use negative values for all of those fields to express application specific hacks.

**Comment by axtimwalde** [comment]
I.e. assume that the positive range of all these fields is that of the signed primitive, not the unsigned.  Sorry.

**Comment by aschampion** [comment]
So for a conformant N5 implementation I'm only required to accept the signed positive range for those values, but am free to treat the negative range as undefined behavior (including rejecting it if I choose). 👍
