### ISSUE TITLE
Zarr meeting today (1/15/2019)?

### ISSUE THREAD

**Issue by DennisHeimbigner** [saalfeldlab/n5#44]
I hope I have the right site. One of you was on
the Zarr meeting this morning and mentioned that
you had what you called the "core API" to isolate
the storage system from higher levels.
Can you point me to, say, an abstract Java class that defines
that API?

=Dennis Heimbigner
  Unidata

**Comment by joshmoore** [comment]
Hi @DennisHeimbigner. I'd assume https://github.com/saalfeldlab/n5/blob/master/src/main/java/org/janelia/saalfeldlab/n5/N5Writer.java is a good starting point, though @axtimwalde may want to correct me. I was looking for something similar and also compared @constantinpape's https://github.com/constantinpape/z5/tree/master/include/z5 but that represents the union of the two APIs rather than the subset that was mentioned.

**Comment by constantinpape** [comment]
> I'd assume https://github.com/saalfeldlab/n5/blob/master/src/main/java/org/janelia/saalfeldlab/n5/N5Writer.java is a good starting point

I also think that the [N5Reader](https://github.com/saalfeldlab/n5/blob/master/src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java) and [N5Writer](https://github.com/saalfeldlab/n5/blob/master/src/main/java/org/janelia/saalfeldlab/n5/N5Writer.java) are good starting points for this.

For z5: there is something akin to a core API for `chunks` for [n5](https://github.com/constantinpape/z5/blob/master/include/z5/io/io_n5.hxx) and [zarr](https://github.com/constantinpape/z5/blob/master/include/z5/io/io_zarr.hxx). 

The API for `data-containers` ended up in the [Dataset class](https://github.com/constantinpape/z5/blob/master/include/z5/dataset.hxx#L26); which unfortunately got a bit bloated over time and is def. not *core*.

If you have more questions about this, feel free to open an issue in the z5 repo.
