### ISSUE TITLE
Store String Used to Create N5 Reader/Writer

### ISSUE THREAD

**Issue by cmhulbert** [saalfeldlab/n5#84]
Currently, there is no consistent way across N5Reader/Writers to query what source was used to open the container. It would be convenient if the N5 API stored the URL used to create the instance, and exposed via an API call, e.g. `getUrl()`.

**Comment by cmhulbert** [comment]
I'd also consider having the URI methods actually return the URI object, instead of the string

**Comment by tpietzsch** [comment]
These ideas sound all good to me.

**Comment by bogovicj** [comment]
in progress: 
https://github.com/saalfeldlab/n5/tree/wip/basePath2Uri

**Comment by bogovicj** [comment]
[This commit](https://github.com/saalfeldlab/n5/commit/de5e8ceebc794c02829f43bdb900fd1e6911a937) adds a test for the behavior of `N5Reader.getURI` and (indirectly) `KeyValueAccess.uri` .  and ensures that `FileSystemKeyValueAccess` behaves as desired.  Do we agree about the expected behavior though?

* MUST begin with a scheme (`file:`, `s3:`, etc)
* MUST be absolute
* MUST be normalized (i.e. not contain (`/./`, `/../`)

**Comment by bogovicj** [comment]
`N5Reader`s now provide a `getURI` that serves this purpose.
